"""adds created at and updated at on item price.

Revision ID: 469c268a1780
Revises: 593b44577625
Create Date: 2024-09-26 21:50:53.158259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469c268a1780'
down_revision = '593b44577625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_prices', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
