"""removes some class models

Revision ID: 593b44577625
Revises: 1d88f33a469e
Create Date: 2024-09-26 21:32:49.133945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593b44577625'
down_revision = '1d88f33a469e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_prices_item_id_items')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_item_prices_store_id_stores')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchases')
    op.drop_table('lists')
    op.drop_table('list_items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('list_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_list_items_item_id_items'),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], name='fk_list_items_list_id_lists'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lists',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchase_date', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='fk_purchases_item_id_items'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_purchases_store_id_stores'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('item_prices')
    # ### end Alembic commands ###
