"""Add attributes to Item model

Revision ID: 834d529628dc
Revises: 2c9eab259c47
Create Date: 2024-09-27 15:04:46.992214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834d529628dc'
down_revision = '2c9eab259c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('group', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('form', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('department', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('size', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('size')
        batch_op.drop_column('department')
        batch_op.drop_column('form')
        batch_op.drop_column('group')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
