"""Fix foreign key reference in orders table

Revision ID: e3c5954cc4d8
Revises: cc0cd1b0d657
Create Date: 2024-10-02 01:24:23.117612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c5954cc4d8'
down_revision = 'cc0cd1b0d657'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_orders_store_id_stores'), 'stores', ['store_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_store_id_stores'), type_='foreignkey')
        batch_op.drop_column('store_id')

    op.drop_table('orders')

    # ### end Alembic commands ###
